name: 自动创建标签并发布 Release

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: 安装 Poetry
        run: pip install poetry

      - name: 安装依赖
        run: poetry install --no-interaction
      
      - name: 获取版本号
        id: get_poetry_version
        shell: pwsh
        run: |
          $version = poetry version -s
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "当前版本: ${version}"
      
      - name: 创建 Git 标签
        if: github.ref_name == 'refs/heads/release'
        shell: pwsh
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          $TAG_NAME="v${{ steps.get_poetry_version.outputs.version }}"
          echo "创建标签: ${TAG_NAME}"

          git tag ${TAG_NAME}
          git push origin ${TAG_NAME}

      - name: 构建 whl
        run: poetry build

      - name: 上传至 Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          tag_name: v${{ steps.get_poetry_version.outputs.version }}
          name: Release v${{ steps.get_poetry_version.outputs.version }}
          generate_release_notes: true
